### ISSUE TITLE
rtx 3080ti low raw speed

### ISSUE THREAD

**Issue by brasrox** [Lolliedieb/lolMiner-releases#1021]
Nvidia aorus 3080 TI 
driver 496.49
Windows10
its does not detecting my gpu as lhr ?
![image](https://user-images.githubusercontent.com/21345109/152622175-722db265-1f13-42b5-9726-859d196ca5e7.png)

im getting very low raw speed in my rtx

![image](https://user-images.githubusercontent.com/21345109/152622196-b92dcb30-aeb6-4409-a9ce-02d6d8212f5d.png)

**Comment by brasrox** [comment]
![image](https://user-images.githubusercontent.com/21345109/152622875-1769b2c3-2f91-46b3-9a7c-6dcfccfd3cbd.png)

**Comment by HeraklesTR** [comment]
i found the solution, give maximum power to power limit bar, reduce memory to 700 mhz and also in miner bat file add this command   --cclk 1200    to lock to core straight 1200mhz. with this code you don need to tune core clock in msi afterburner. in order to get better results from lhr cards, core clock must be very stable and not move. this way i am able to get 79 mh eth and 1.9gh ton mining speed in windows. good luck bro.

**Comment by jgonzis** [comment]
> i found the solution, give maximum power to power limit bar, reduce memory to 700 mhz and also in miner bat file add this command --cclk 1200 to lock to core straight 1200mhz. with this code you don't need to tune core clock in msi afterburner anymore. in order to get better results from lhr cards, core clock must be very stable and not move. this way i am able to get 80 mh eth and 2.1gh ton mining speed in windows with my 80 ti game rock. Also always use 472.12 driver for better lhr stability. good luck bro.

Totally right... 

Also 1.44 should help on that too
