### ISSUE TITLE
double free or corruption fasttop v1.43 linux. Memory leak

### ISSUE THREAD

**Issue by mpmedearis** [Lolliedieb/lolMiner-releases#1064]
Dual mining eth and ton. Linux. Miner stops after a few hours and double free or corruption fasttop is on the screen

**Comment by coofcookie** [comment]
Same issue. Double free or corruption (out) for me.

**Comment by m2internet** [comment]
Same here, the timing of the memory error is intermittent. Sometimes runs for hours, others under an hour.  I'm running pretty OC'd tho so im assuming its due to the overclocks. If Ii keep getting it I'm gonna scale back the overclocks to see if it mitigates the error. 
Rig running on HIVEOS latest version of lolminer 1.43:
3 - 3070 FHR - Core: 1500, Mem: 2600 = 61.55MH ETH & 1.631 GH TON
5 - 6600XT Samsung Memory - Core: 2000, VDD: 0, VDDCI: 825, MVDD: 1325, Memory: 1100
2 - 6600XT Micron Memory - Core: 2000, VDD: 0, VDDCI: 825, MVDD:1325, Memory: 1065
Hashrates:
405.4 MH ETH - HiveOn Pool
13.38 GH TON - Ton Whales pool

**Comment by snoby** [comment]
Same issue, this leads to high LA.  Happens mainly on my AMD rig and my Nvidia rig that is 12 cards, the others are fine.  Both of those have the small celeron processor.

**Comment by jgonzis** [comment]
> Dual mining eth and ton. Linux. Miner stops after a few hours and double free or corruption fasttop is on the screen

Don't use Tonwhales... that's the problem of the corruption, pool is blocking and then miner crash. It will be solved for next release. But meanwhile Tonwhales doesn't improve that block from cloudfare use other pools like ton-pool.com or toncoinpool.io
