### ISSUE TITLE
problem with LHR ETH hashrate

### ISSUE THREAD

**Issue by telethrasher** [Lolliedieb/lolMiner-releases#1069]
working on it still after reading comments - 
5x 3060ti LHR
ETH 42.7mh/s
TON 1250mh/s
normal TON was 2000mh/s using lolminer 1.42 core clock 1780 - 1795 with nvidia-smi
got the core lock at 1550 now

**Comment by mohsenk94** [comment]
I don't totally understand the problem.
Are you saying "Why isn't LOL miner hashing at 2000MH/s on ton" now?
The reason is it's Dual mining ETH as well. It's using some of the GPU on ETH and some on TON.
it does affect both algorithms , be it a small percent , but it does affect it
The hashrates you reported are actually quite good.

**Comment by jgonzis** [comment]
> working on it still after reading comments - 5x 3060ti LHR ETH 42.7mh/s TON 1250mh/s normal TON was 2000mh/s using lolminer 1.42 core clock 1780 - 1795 with nvidia-smi got the core lock at 1550 now

That normally happens because the PL is not at 100%... 

Try new 1.44
