### ISSUE TITLE
Dual mining will not stop detecting Mining lock

### ISSUE THREAD

**Issue by RobKerstetter** [Lolliedieb/lolMiner-releases#1106]
Dual mining ton coin Miner keeps detecting mining lock is there a way to fix this

**Comment by javsezlol1** [comment]
Hey man, just had this same issue ! i updated to latest drivers even though they recommend using the one 472.12 drivers seemes to have fixed it will update again in about an hour too see if it has fully worked instead of getting lhr lock deteced i just keep getting the suto tuning which is a good sign id say

**Comment by javsezlol1** [comment]
also try lowering your memory clock by 200 and increase slowly till that message goes away

**Comment by RobKerstetter** [comment]
yeah i went to 472.12 lowered the core clock and its working now

**Comment by jgonzis** [comment]
Try lolMiner 1.44 , it should solve several of the problems. https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.44
