### ISSUE TITLE
3060ti eth ok but ton 0mh with windows v.1.44

### ISSUE THREAD

**Issue by bilemedimki** [Lolliedieb/lolMiner-releases#1158]
![Ekran Alıntısı2](https://user-images.githubusercontent.com/92214134/153033598-c38b9bdd-8a61-4491-986b-638bbd70401f.JPG)
![Ekran Alıntısı1](https://user-images.githubusercontent.com/92214134/153033640-adbfcc8d-80ba-4b9f-912a-f0ef6513eef0.JPG)

**Comment by bilemedimki** [comment]
nvidia 472.12

**Comment by jgonzis** [comment]
> ![Ekran Alıntısı2](https://user-images.githubusercontent.com/92214134/153033598-c38b9bdd-8a61-4491-986b-638bbd70401f.JPG) ![Ekran Alıntısı1](https://user-images.githubusercontent.com/92214134/153033640-adbfcc8d-80ba-4b9f-912a-f0ef6513eef0.JPG)

Your problem is that you are not using Fixed Core ... and you haven't got PL to 100%

Could you please add in the new bat file of 1.44:

in EXTRAPARAMETERS --cclk 1500

Remember to put lolminer.exe as administrator and PL to 100% in MSI Afterburner please... 

You have to see something like this but with 1500, if it doesn't show that at startup check:

- bat file is the new one
- lolMiner.exe run as administrator

![image](https://user-images.githubusercontent.com/38668405/153042127-2e9272e1-1a67-4f58-9bd5-e7c3784c590b.png)
