### ISSUE TITLE
3060 V1 dual mining eth and ton

### ISSUE THREAD

**Issue by Messa1** [Lolliedieb/lolMiner-releases#1166]
I'm using the dev driver for nvida on windows.
All cards get good mhs on eth and also on ton.
The only card which don't work "right" is my 3060 V1.
I'm using nvidia dev driver 470.05 and hdmi dongle on this card, so that i got full hashrate for eth.

3060 got 46.82 mhs on TON
2060 got 313.69 mhs on TON 

![3060](https://user-images.githubusercontent.com/3908658/153060188-aafb902c-4f37-4781-ab90-2e9ecd457e68.png)
![3060](https://user-images.githubusercontent.com/3908658/153060194-216c9bdc-2b29-4541-93ff-e11808c813f1.png)

**Comment by jgonzis** [comment]
> I'm using the dev driver for nvida on windows. All cards get good mhs on eth and also on ton. The only card which don't work "right" is my 3060 V1. I'm using nvidia dev driver 470.05 and hdmi dongle on this card, so that i got full hashrate for eth.
> 
> 3060 got 46.82 mhs on TON 2060 got 313.69 mhs on TON
> 
> ![3060](https://user-images.githubusercontent.com/3908658/153060188-aafb902c-4f37-4781-ab90-2e9ecd457e68.png) ![3060](https://user-images.githubusercontent.com/3908658/153060194-216c9bdc-2b29-4541-93ff-e11808c813f1.png)

We found several 4060v1... should be something in the tune... could you put them really high Core Fix?

for example, high core fix to 1650 in 3060 and PL to 100, play with fixed core and PL to 100%...

Sure that will help

**Comment by Messa1** [comment]
I change PL - and that helps now they on 120 watt. But they all have different mhs - i got a second rig with 3060 in 
![Screenshot_20220208-214132](https://user-images.githubusercontent.com/3908658/153072226-5ed72593-5a82-4cf6-95f6-7a338a973d0f.jpg)

**Comment by ltwarrior18** [comment]
It should use 140-170 watts. 1100 clock speed is not enough for Ton. Core clock are bellow recommended 1500-1800, sometimes I go beyond recommended and add extra +100(1900) (If I am correct). You need to increase wattage through higher voltage and power limits. When you limit power downwards it will prioritize mem speed above clock speed, and if needed it will start dropping voltages. Also rtx 3060 loves default clock curve and increased voltages, if you need more clock just increase voltages. But if you just increase clocks without voltages it won't mine more as it needs more juice to go that fast. Also instead of locking voltage, just use pl. At first you can run try to run at max, than start limiting pl by 1% and check if hash rates dropped significantly, if not drop again, or find your best efficiency. But 119 watts is an indicator that you don;t give the guy enough voltage juice, or limited pl too much. Also rigs needs to be restarted with new clock, mem, pl values, to tune out at the beginning and find the best results, also different cards have different silicon - so it's a lottery

**Comment by ltwarrior18** [comment]
Oh yeah I remember there is like a bug on 3060, it mines ton like 166 sometimes 378 or similar results, when it should be kicking ~800 or even 1100 or more on better 3060s, sometimes restart fixes it, sometimes again playing with different overclock profiles fixes it for good, just try to remember profile settings that worked well and switch to those settings. Experimenting is preferable, and a separate rig for continuous mining on all other cards.

**Comment by Messa1** [comment]
I will try on my rig with just one 3060 on it. Yeah i know that they want more watt . Im no higher 140 watt. I will get back with some tests :)

**Comment by jgonzis** [comment]
We think is a bug with the driver 470.05 and 3060v1

**Comment by Messa1** [comment]
Yes could be - but I don't switch cause oh eth hashrate

**Comment by ltwarrior18** [comment]
Yeah it might be possible somekind of random bug. I used lhr off paramaters, and maybe if you have huge 3060 mining rig, you would want to mix them around and/or put in smaller rigs, to diversify errors. Lhr off paramater helps me, if I play games at the same rig, it won't start suddenly tuning, due to mhs drop.

**Comment by jgonzis** [comment]
> Yes could be - but I don't switch cause oh eth hashrate

Try to put without any powerlimit and a high Core like 1650...

**Comment by Messa1** [comment]
I got now this out of one 3060 (Windows + dev driver)

PL - none
CC fixed at 1250
MEM  +1300

134 W
eth about 48 MH/s
ton about 600 MH/s

![3060](https://user-images.githubusercontent.com/3908658/153156294-5916e16c-41f8-4ce8-b5ab-5bdda583e223.png)

**Comment by jgonzis** [comment]
> I got now this out of one 3060 (Windows + dev driver)
> 
> PL - none CC fixed at 1250 MEM +1300
> 
> 134 W eth about 48 MH/s ton about 600 MH/s
> 
> I will test it if not stable - i will post some other settings :)
> 
> ![3060](https://user-images.githubusercontent.com/3908658/153156294-5916e16c-41f8-4ce8-b5ab-5bdda583e223.png)

Many thanks for sharing
