### ISSUE TITLE
Problem in loading kernel and cant detect my RADEON RX580 GPU

### ISSUE THREAD

**Issue by dverzon1** [Lolliedieb/lolMiner-releases#120]
Hi, how to fix the error says "problen in loading kernel" and didnt read my other gpu. I have two gpu NVIDIA GeForce GT730 and RADEON RX 580 Series

**Comment by Lolliedieb** [comment]
The gt730 is a 2G card of the Kepler generation. It currently may run on BTG mining, but even there not sure. Except for this I think there is no algorithm in the miner that will work with 2G.

With regard to the rx 580 cards: Please run clfinfo (or clinfo.exe in WIndows) which ships with the AMD OpenCL driver and paste me the output here.  I will try to see what might go on why the miner struggles to load kernel on your cards (the clinfo gives detailed information about the driver version and all data the miner uses to detect cards - so that would be exceptionally helpful)

**Comment by Sharp-Rock** [comment]
im also using a gt730 4g and its detected but i get a kernel loading problem

**Comment by Kitch72** [comment]
Hi,

I got the error message with a Nvidia Geforce 820M with 2Gb memory. Is there anything to do to use lolminer or the card is too weak?

Thanks

**Comment by MorganSzucs** [comment]
Has there been a fix for this?  I am trying to run a GTX-760 4GB and it says:
Setup Miner...
Device 0:
    Name:    GeForce GTX 760
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  4096 MByte
    Problem in loading kernel

**Comment by jeimigarcia** [comment]
> Has there been a fix for this? I am trying to run a GTX-760 4GB and it says:
> Setup Miner...
> Device 0:
> Name: GeForce GTX 760
> Address: 1:0
> Vendor: NVIDIA Corporation
> Memory: 4096 MByte
> Problem in loading kernel

I have same issue as you, but mine is **NVIDIA GeForce 480M 4096MByte**

**Comment by Lolliedieb** [comment]
GTX 7xx and 4xxM series are Fermi & Kepler generation and thus pretty old.
Right now I see no way of porting my kernels to this, because I need at
least Maxwell and newer instruction / feature set.

Am Mi., 24. März 2021 um 08:53 Uhr schrieb jeimigarcia <
***@***.***>:

**Comment by decapty** [comment]
Please l need help how do l go about this iinformation 

Setup Miner...
Device 0:
    Name:    NVS 5200M
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Memory:  1024 MByte
    Problem in loading kernel

**Comment by jgonzis** [comment]
Too old GPU not supported
