### ISSUE TITLE
VRAM Temp Needed - 3000 Series Run Hot

### ISSUE THREAD

**Issue by CryptoLLC** [Lolliedieb/lolMiner-releases#1200]
Can you guys add vram temp support to the api? We base our power setting on the vram temp. Right now we cant use LOL  Miner unless vram is added. Please add this feature. Thank you.

**Comment by HeraklesTR** [comment]
up! i wait this very basic improvement from so long, but they too lazy to implement. come on, @Lolliedieb your competitors had this feauture like months (trex, gminer, nbminer etc.) the only reason i use windows is seeing vram temps, we are not minority who wants this very basic improvement, basically all windows users will be happy about it! do it!

**Comment by jgonzis** [comment]
> up! i wait this very basic improvement from so long, but they too lazy to implement. come on, @Lolliedieb your competitors had this feauture like months (trex, gminer, nbminer etc.) the only reason i use windows is seeing vram temps, we are not minority who wants this very basic improvement, basically all windows users will be happy about it! do it!

The problem is that they use directly the library of anothers... a closed code, if it was open source we will use it, but lolMiner don't steal the job of others. . You can use that software thay they link, like GPU-Z or HWInfo64. 

Until is opened or one of that closed software open to lolMiner the option to use it, lolMiner will not steal the work of others.

**Comment by CryptoLLC** [comment]
I dont want to use other software. Vram temps should be built into the miner its self and shown on an html page such as localhost/stats.
People that use hiveos on 3000 series are making a huge mistake since they cant see their vram and are most likley frying their vram chips. Hitting 110c all the time. This is unacceptable for us so we use Gminer to see vram and fetch vram temps from json file. Then we power down the cards using a bat file. None of our cards ever, ever, ever overheat no matter the temperature outside. Why is this so hard to do? Just add it and be done with it. Right now this is a deal breaker with lolminer. No vram temps no lolminer on our 1200+ gpu mining farm. Our farm is only 3000 series.

**Comment by Lolliedieb** [comment]
Well ... "lazy" in this sense ... is not appropriate ;)
Problem is there is only one library of hwinfo24 that can do it. But the
license prohibits to use that in any commercial application. So - what are
the others doing? Violating it heavily. And since I am coding alone I do
not really have the capacity to code it on my own ans spend my time rather
on new GPU codes ...

Am Do., 10. Feb. 2022 um 09:58 Uhr schrieb HeraklesTR <
***@***.***>:

**Comment by CryptoLLC** [comment]
Why dont you just hire coders? You make plenty of money so it should not be an issue. As for hwinfo24 why dont you ask them for a special deal? They might say yes. Gminer and Trex miner both have vram. This is a huge deal breaker for our farm. We need vram or we cant use the miner.
