### ISSUE TITLE
1.18a Windows version has a Trojan:Script/Wacatac.B!ml again

### ISSUE THREAD

**Issue by Cleinor** [Lolliedieb/lolMiner-releases#123]
![image](https://user-images.githubusercontent.com/13948364/103954765-3349cd00-5145-11eb-93c3-deba985273c8.png)

1.17 was good

**Comment by Lolliedieb** [comment]
There is one difference between 1.17 and 1.18 and this is about the range the API is Opened to resolve issue #111.
I am sad that this Antivirus tools miss-detect the miner, but can not do much about it - I even signed the damn executable so its verifiable it is unmodified since it left my computer. I did not code a Virus or Trojan in.
