### ISSUE TITLE
Miner doesn't restart when there is no internet for some time

### ISSUE THREAD

**Issue by Juriyx** [Lolliedieb/lolMiner-releases#1406]
I had no internet for about 5-7 minutes and lolMiner 1.46a hasn't restarted. As result, two NVIDIA cards showed 0 MH/s hash rate and didn't send any shares to the Binance pool.
OS: RaveOS

**Comment by bitcoincff** [comment]
I am using lolminer and when there is an error reboot.sh is not executed. is waiting for something.

**Comment by bitcoincff** [comment]
I am using lolminer and when there is an error reboot.sh is not executed. is waiting for something. I see reboot.sh and emergency.sh in the lolminer folder. but it does not execute it or something happens because it is waiting. If it didn't find it, it would show an error message, even I have intentionally changed to rebbot.sh and there it does give an error. I'm root and it still doesn't work.
