### ISSUE TITLE
1.48 Error: Your input to --pool "eu1-zil.shardpool.io:5555" can not be split into a address and a port. Please use format <pool address>:<pool port>.       

### ISSUE THREAD

**Issue by Sanchous98** [Lolliedieb/lolMiner-releases#1554]

**Comment by Gkozd** [comment]
"
@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

**set "POOL=stratum+ssl://eu1.ethermine.org:5555"**

set "**WALLET=XXX.xxx.XXX (yours)**"										

set "EXTRAPARAMETERS="

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

if exist "%CD%\lolMiner.exe" goto infolder
echo "Searching for lolMiner.exe, because is not in this folder.That could take sometime..."
for /f "delims=" %%F in ('dir /b /s "C:\lolMiner.exe" 2^>nul') do set MyVariable=%%F
if exist "%MyVariable%" goto WindowsVer
echo "lolMiner.exe is not found in the system, that could be blocked by Windows Defender or Antivirus "
goto END

:infolder
set MyVariable=%CD%\lolMiner.exe


:WindowsVer
echo "Running lolMiner from %MyVariable%"
for /f "tokens=4-5 delims=. " %%i in ('ver') do set VERSION=%%i.%%j
if "%version%" == "10.0" goto W10
goto OtherW

:W10
"%MyVariable%"  --algo ETHASH --pool !POOL! --user !WALLET!   --watchdog exit !EXTRAPARAMETERS!
if %ERRORLEVEL% == 42 (
	timeout 10
	goto W10
)
goto END

:OtherW
"%MyVariable%"  --algo ETHASH --pool !POOL! --user !WALLET!--watchdog exit !EXTRAPARAMETERS! --nocolor
if %ERRORLEVEL% == 42 (
	timeout 10
	goto OtherW
)

:END
pause
"

**Comment by Sanchous98** [comment]
> Windows? Version? ZIL only or ZIL+ XYZ ?

HiveOS, ETH+ZIL

**Comment by jgonzis** [comment]
You have do the right flightsheet. Put a photo of the flightsheet to see where is the error
