### ISSUE TITLE
using --4g-alloc-size makes dag not genrate 

### ISSUE THREAD

**Issue by yahia20** [Lolliedieb/lolMiner-releases#156]
I am using 5500xt 4gb amdgpu-pro 20.40 when connecting to a pool it gave me a hash rate of 0 sand dag never said it has finished so I then tried benchmarking epoch 385 same error. then 255 to try to debug ,it worked fine giving the expected hash rate but when I use --4g-alloc-size 4000 makes dag not genrate although it uses much lower dag size than 4000MB ~3GB using --keep-free gives same error why does it take so long should I just what till it generates dag when mining ?

**Comment by yahia20** [comment]
after some time dag is complete but still 0 hash rate

**Comment by jgonzis** [comment]
You could try to active the intern GPU of Intel... that will let more free memory on the GPU and let you some option to mine...

**Comment by yahia20** [comment]
I don't have an internal gpu only external

**Comment by Lolliedieb** [comment]
Hmm ... what OS you are on?
On Linux it might be possible to go mining with a 4G card without external graphic card, but overall it is rather unlikely to work. Make sure your cards mining do not also do screen output, especially on Windows. Else if this is not possible I only can suggest to switch your mining to ETC, because that uses substantially less memory and even works in Windows with screen to card connected.
