### ISSUE TITLE
Having Issues Running lolMiner 1.40 on my laptop

### ISSUE THREAD

**Issue by OlamideBorex** [Lolliedieb/lolMiner-releases#1572]
![IMG_20220510_091539_659 1](https://user-images.githubusercontent.com/104477348/167584790-9ec2de6b-dbd3-4d10-869a-fc67b9b54f2c.jpg)
Hello everyone, I'm new here. Please can anyone help with this. thanks

**Comment by UselessGuru** [comment]
It seems you are trying to mine ethash.... this requires at least 5GB of memory.

https://minerstat.com/dag-size-calculator

**Comment by OlamideBorex** [comment]
> 

thanks. could you please put me through necessary steps/guidelines/requirements if you don't mind, cos I'm new to this and I really don't have any idea. Thank you!

**Comment by OlamideBorex** [comment]
> It seems you are trying to mine ethash.... this requires at least 5GB of memory.
> 
> https://minerstat.com/dag-size-calculator
> 
> 

thanks. could you please put me through necessary steps/guidelines/requirements if you don't mind, cos I'm new to this and I really don't have any idea. Thank you!

**Comment by UselessGuru** [comment]
You cannot use your computer to mine Ethash because your GPU does not have enough memory.

You can mine other Coins / Algorithms, but they will not be profitable unless you have free electricity.
Feel free to have a look at my project:
[https://github.com/Minerx117/NemosMiner/tree/master](https://github.com/Minerx117/NemosMiner/tree/master)
Download
[https://github.com/Minerx117/NemosMiner/archive/refs/heads/master.zip](https://github.com/Minerx117/NemosMiner/archive/refs/heads/master.zip)

**Comment by jgonzis** [comment]
> ![IMG_20220510_091539_659 1](https://user-images.githubusercontent.com/104477348/167584790-9ec2de6b-dbd3-4d10-869a-fc67b9b54f2c.jpg) Hello everyone, I'm new here. Please can anyone help with this. thanks

That igpu is not supported, you need it a dedicated
