### ISSUE TITLE
Is there any way to combine --devices AMD command with --devices 1 command?

### ISSUE THREAD

**Issue by KralMurat** [Lolliedieb/lolMiner-releases#1665]
I have a NVIDIA-AMD combined rig, mining ETH. I'd like to use lolMiner for only AMD 8GB cards. But also I'd like to add AMD 4GB cards in the same rig, and mine ETC with them. So I need to specify --devices AMD and also I need to specify which AMD cards I want to mine with lolMiner. 

When I try to use:

--devices AMD
--devices 1

I'm getting an error something like:

 "devices" command can't be used multiple time

So is it possible to determine which AMD cards should be used with lolMiner?

**Comment by KralMurat** [comment]
okay I found how to
It works like this 
--devices AMD--devices 1

**Comment by KralMurat** [comment]
Nope, it doesn't like this, If I do this, lolMiner catches the NVIDIA 1 device :) not AMD 1.

**Comment by Kostas-13** [comment]
I also have Nvidia and AMD cards.. in my case
gpus 0-6 .. and from those 7 cards 1 and 6 is nvidia (which I do wanna run with LoLminer=>
I use this command: --devices "1,6"
I don't use the AMD command at all, hope it helps mate.

**Comment by KralMurat** [comment]
but when you specify --devices "1,6" without AMD or NVIDIA, how does lolMiner knows which 1,6 it'll take, I have NVIDIA cards in 1,6 too. I'll give it a try but without specifying the AMD or NVIDIA, I don't know how miner takes because as you know AMD and NVIDIA cards both stars from GPU0, separately.

**Comment by Kostas-13** [comment]
Forget about nvidia and amd.. no they don't start separately xD
eg.  You have 11 cards (0-10)
At lolminer u want 0,3,11 .. u just do --devices "0,3,11" 
It's about PCI BUS and windows management at regedit where the cards are, lolminer just read there the positions and you can see them when you startup lolminer. The only prob by doing this will be in a case you take off one card from the system or dead gpu. 
You will have to reconfigure the cards and specify which to run again, because if 1 or more missing numbers will change.

**Comment by KralMurat** [comment]
Ah I see, good to know :) I was thinking miner is using the GPU 0, GPU 1 etc, not the order in the screen. 
Thanks I'll try that approach, and yeah I'll take into account when I change the order or add/remove card

**Comment by jgonzis** [comment]
No, nice point but you have to do a big line selection of Devices...
