### ISSUE TITLE
0MH/S Started last night 12:00 around that GMT +8

### ISSUE THREAD

**Issue by jeffpatel71** [Lolliedieb/lolMiner-releases#168]
Now whenever, I start my miner. After only a few minutes I begin to get a bunch of errors then get the execute emergency code. And afterwards have a speed of 0MH/s. I'm using an RTX 3060ti for mining. I am using lol miner v1.19

**Comment by jgonzis** [comment]
> Now whenever, I start my miner. After only a few minutes I begin to get a bunch of errors then get the execute emergency code. And afterwards have a speed of 0MH/s. I'm using an RTX 3060ti for mining. I am using lol miner v1.19

You should put the OC that you are applying to the card ... That could be too much Overclock on the memory... that make a crash... 

Can you put some screenshoot?

**Comment by stevepresley** [comment]
You're definitely running out of power due to the OC settings.  Are you using AfterBurner?

**Comment by jeffpatel71** [comment]
![image](https://user-images.githubusercontent.com/77821959/105577620-c164bb00-5db5-11eb-8b2c-c2e36e005c76.png)

**Comment by jeffpatel71** [comment]
So i get this and then 
![image](https://user-images.githubusercontent.com/77821959/105577632-cf1a4080-5db5-11eb-80f5-3b461fc581f9.png)

**Comment by jeffpatel71** [comment]
![image](https://user-images.githubusercontent.com/77821959/105577639-d8a3a880-5db5-11eb-8c60-1c8b1c83e75c.png)
Msi afterburner config

**Comment by jgonzis** [comment]
Sometimes it could be a Windows crash, driver crash probably, a fast solution is to have a loop...

:loop
Lolminer.exe --algo ETHASH....
goto loop

It automatically restart without loosing time
Then it autorestart the miner...

**Comment by jeffpatel71** [comment]
> Sometimes it could be a Windows crash, driver crash probably, a fast solution is to have a loop...
> 
> :loop
> Lolminer.exe --algo ETHASH....
> goto loop
> 
> It automatically restart without loosing time
> Then it autorestart the miner...

I'm sorry I'm very new to crypto mining where do I put this code?

**Comment by jgonzis** [comment]
> > Sometimes it could be a Windows crash, driver crash probably, a fast solution is to have a loop...
> > :loop
> > Lolminer.exe --algo ETHASH....
> > goto loop
> > It automatically restart without loosing time
> > Then it autorestart the miner...
> 
> I'm sorry I'm very new to crypto mining where do I put this code?

In the bat file that you click to run eth... the one you have modify to put your Wallet 😀

**Comment by clamatac** [comment]
where exactly in the bat file?

@echo off

setlocal enableDelayedExpansion

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eu1.ethermine.org:4444"
set "WALLET=XXXX.yyyy"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! 
pause


Thanks in advance

**Comment by jgonzis** [comment]
Rem #################################

:loop
lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET!
goto loop

:-)

**Comment by jgonzis** [comment]
An easy solution that will detect if miner crash or miner is 0... is to use this bat file...  instead of the mine_eth.bat 

It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better


@echo off

setlocal enableDelayedExpansion
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

:loop
REM start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444


:mining
timeout 120
type NUL > %file%
type NUL > %tmpfile%
echo Proving Stats, press CTRL-C and Y to Quit!
certutil -urlcache -split -f %url% %file%

fc %file% %tmpfile% > nul
if errorlevel 1 (goto online) else (goto crash)

:online
findstr "Performance_Summary" %file% > %tmpfile%


FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x

for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)

:restart
echo "Killing Process"
taskkill /IM "lolMiner.exe" /F
echo "Restarting lolMiner"
goto loop

:crash
echo "LolMiner Not Running, restarting lolMiner"
goto loop

**Comment by clamatac** [comment]
thanks a lot, I will try it

**Comment by jgonzis** [comment]
@stevepresley you are a master making bat file... could you improve it??

**Comment by stevepresley** [comment]
> @stevepresley you are a master making bat file... could you improve it??

Your batch file will work fine, as long as you don't have to run two instances due to the double card mining slow down though!

I gave up on a BAT file and started writing a Windows EXE. (and then found AwesomeMiner which does what I was planning to do and is much further down the path than I could care to go for $4/month).

As an aside, I'm discussing the dual card issue with the developer of AwesomeMiner as his software also doesn't start independent threads to get around the throttling issue, and if I setup two miner threads, it tries to use the same API port for both, which means one will not run as the port is already in use.  Will update if he can sort that out in short order.

**Comment by Clankcoll** [comment]
Well i made it a bit Simpler i still need to test and look it up in "production"

i added to my emergency.bat 


setlocal enableDelayedExpansion

Rem ##################################
Rem ## Emergency script in case the ##
Rem ## miner crashes. User defined  ##
Rem ## actions to be inserted here  ##
Rem ##################################

taskkill /im "lolMiner.exe" /F

C:\Users\{user}\Desktop\lolMiner_v1.21_Win64\1.21\mine_etc.bat


since the watchdog starts anyway the emergency script i am using it to kill the instance wich has a crashed card detected and restarts the miner should work fine but i will update it seemed a simpler thing to do

**Comment by jgonzis** [comment]
Finally solution. 

You can try new 1.25 Lolminer with special CUDA version great for Windows, and less problems with multiple GPU.

[https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25](https://github.com/Lolliedieb/lolMiner-releases/releases/tag/1.25)
