### ISSUE TITLE
Try to skip AMD card in config.

### ISSUE THREAD

**Issue by Turnyban** [Lolliedieb/lolMiner-releases#1791]
I have four AMD and four Nvidia on my rig. I want to skip the 5 first in the config.
Is it right like that ?
--cclk * ,* ,* ,* ,* ,1470,1470,1470
--mclk * ,* ,* ,* ,* ,810,810,810
or i need to write:
--devices arg 6,7,8
--cclk 1470
--mclk 810

How can i skip my 5 firts card in argument parameter? thanks

**Comment by Lolliedieb** [comment]
In your case you can - at the moment - just write --cclk 1470 --mclk 810 - because the amds will ignore it.
This may change in the future though.

Your first guess was right though, just make sure you have no spaces in the list...
So 
--cclk *,*,*,*,*,1470,1470,1470
--mclk *,*,*,*,*,810,810,810
is the way to write it :)
