### ISSUE TITLE
ver. 1.65a kaspa mining invalid shares

### ISSUE THREAD

**Issue by bekman1** [Lolliedieb/lolMiner-releases#1823]
Hi dev, just update my linux rig to ver. 1.65a. The issue with stale/invalid shares on Kaspa on Nicehash is not 100% solved. Arround 4-5% of shares is still invalid.

Regards.

**Comment by Radeon888** [comment]
me too.. duplicate share on nicehash stratum is too high about 10%.. dev please fix it

**Comment by bekman1** [comment]
Found this by GMiner Github issues. Users who mining single Kaspa on Nicehash reporting same problem. 

Gminer devs answer:
look at log, sometimes nicehash select 4 bytes for extranonce, we have only 4 bytes to find solution, 4 bytes = 2^32 = 4 294 967 296 hashes, 3090 ~ 1.2 GH/S, 4 x 3090 may check all 2^32 nonces in one second, sometimes nicehash not send new job 2-3 seconds, it's nicehash issue, we cannot solve it, they should use less bytes for extranonce, 2-3 

Maybe lolMiner invalid shares have the same reason?

**Comment by bekman1** [comment]
and yes, on my rigs where only 4x3060 cards, i not have problem with duplicate shares.

**Comment by Lolliedieb** [comment]
There will be no fix by us, because the problem is by Nicehash. As stated correctly by the other developers the reason is that Nicehash since ~last 3 days sometimes gives 4 bytes of extra nonce narrowing the space for the miner software too much down, so what happens is that we did mine through all available nonces too quickly and then duplicate shares happening, because same nonce as before gets processed again.
