### ISSUE TITLE
New Dag RTX 3000 mh/s goes down to 0

### ISSUE THREAD

**Issue by wololo34** [Lolliedieb/lolMiner-releases#183]
When a new bigger DAG is being loaded my RTX 3090's hash rate gets stuck at 0 (confirmed by my pool), while my other cards (AMD - vega 64, 480, 570) carry on as usual

Side note:
I have found this miner to be the best for my RTX card, (123mh/s+) and no crashes. 

Thanks, 
wololo

**Comment by jgonzis** [comment]
An easy solution that will detect if miner crash or miner is 0... is to use this bat file...  instead of the mine_eth.bat 

It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better


@echo off

setlocal enableDelayedExpansion
set url=http://127.0.0.1:4444
set file=lolMiner.json
set tmpfile=Perfomance.json

Rem #################################
Rem ## Begin of user-editable part ##
Rem #################################

set "POOL=eth.2miners.com:2020"
set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"										

Rem #################################
Rem ##  End of user-editable part  ##
Rem #################################

:loop
REM start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444


:mining
timeout 120
type NUL > %file%
type NUL > %tmpfile%
echo Proving Stats, press CTRL-C and Y to Quit!
certutil -urlcache -split -f %url% %file%

fc %file% %tmpfile% > nul
if errorlevel 1 (goto online) else (goto crash)

:online
findstr "Performance_Summary" %file% > %tmpfile%


FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x

for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)

:restart
echo "Killing Process"
taskkill /IM "lolMiner.exe" /F
echo "Restarting lolMiner"
goto loop

:crash
echo "LolMiner Not Running, restarting lolMiner"
goto loop

**Comment by wololo34** [comment]
cheers thanks!

**Comment by bobbybean** [comment]
> An easy solution that will detect if miner crash or miner is 0... is to use this bat file... instead of the mine_eth.bat
> 
> It will check in the API of the miner if it is working or not each 120seconds... I hope it helps :-) fell free to inform if not works to try to do it better
> 
> @echo off
> 
> setlocal enableDelayedExpansion
> set url=http://127.0.0.1:4444
> set file=lolMiner.json
> set tmpfile=Perfomance.json
> 
> Rem #################################
> Rem ## Begin of user-editable part ##
> Rem #################################
> 
> set "POOL=eth.2miners.com:2020"
> set "WALLET=0x155da78b788ab54bea1340c10a5422a8ae88142f.lolMinerWorker"
> 
> Rem #################################
> Rem ## End of user-editable part ##
> Rem #################################
> 
> :loop
> REM start lolMiner.exe --algo ETHASH --pool !POOL! --user !WALLET! --apiport 4444
> 
> :mining
> timeout 120
> type NUL > %file%
> type NUL > %tmpfile%
> echo Proving Stats, press CTRL-C and Y to Quit!
> certutil -urlcache -split -f %url% %file%
> 
> fc %file% %tmpfile% > nul
> if errorlevel 1 (goto online) else (goto crash)
> 
> :online
> findstr "Performance_Summary" %file% > %tmpfile%
> 
> FOR /F "tokens=* delims=" %%x in (%tmpfile%) DO echo %%x
> 
> for /f "tokens=* delims= " %%a in (%tmpfile%) do set str=%%a
> if "%str%"==""Performance_Summary": 0.00," (goto restart) else (goto mining)
> 
> :restart
> echo "Killing Process"
> taskkill /IM "lolMiner.exe" /F
> echo "Restarting lolMiner"
> goto loop
> 
> :crash
> echo "LolMiner Not Running, restarting lolMiner"
> goto loop

Thanks for this, however I get this issue, see screenshot below: 
[https://ibb.co/qRmkxWV](url)

Note when I start the .bat file my antivirus picks it up, so i made an excpetion. Still getting this tthough. Hope to resolve this as the mining stops randomly - somettimes  10 mintes, 30 mins, 12 hours etc..

**Comment by jgonzis** [comment]
I have correct the script it was with a REM before the miner not launching the miner...

**Comment by jgonzis** [comment]
Try new Cuda Solver, more stable and works with watchdog
