### ISSUE TITLE
0.8.5 stolen 1063

### ISSUE THREAD

**Issue by Quake4** [Lolliedieb/lolMiner-releases#20]
![image](https://user-images.githubusercontent.com/29517243/61530641-52bed880-aa2d-11e9-8b46-c5a5d9a57b95.png)

![image](https://user-images.githubusercontent.com/29517243/61530978-3bccb600-aa2e-11e9-88d8-b9580f5a9ed6.png)

it was in 0.8.3

**Comment by Quake4** [comment]
same issue #19

**Comment by MaynardMiner** [comment]
I am having same issues. It seems lolminer on windows cannot distinguish gpu platforms anymore, unless instructions changed and I missed.

**Comment by Lolliedieb** [comment]
Interesting - is it still there when you currently run 0.8.3? Since you got a 560 installed can you run clinfo.exe to see if that little tool (shipped with amd drivers) can find the 1060? Because that uses just standard functions to search for cards. 

If both 0.8.3 and clinfo do not see it, it maybe that somehow the Nvidia OpenCL driver is gone - whyever...

**Comment by Quake4** [comment]
yes, clinfo show only rx560. haw i can fix it, just reinstall nvidia driver?
