### ISSUE TITLE
lolminer 1.21: stops running at random

### ISSUE THREAD

**Issue by Syn-Ergi** [Lolliedieb/lolMiner-releases#281]
Whenever I turn on the lolminer, it will mine anywhere between 2 to 45 minutes before prompting to press any key to continue. This has been going on for about 3 days now and I have not changed anything on my computer in the last week. I have an Asus Tuf 3060ti and using the us1.ethermine.org. Any help will be greatly appreciated since micromanaging this is killing my rates.

If any more info needed I will supply :D 

Best,
SynErgi

**Comment by jeromel1978** [comment]
I have been getting the same error when mining Beam on my RX 5600 XT.  It seems random to me too since temperatures look like they are within good ranges (all under 90 degrees easily).

Here is the dump when prompted to "Press any key to continue"

New job received: 2185029 Difficulty: 512
0x00007FF71A0DE51C (0x0000030D92F88D57 0x0000343437353132 0x0000343437353132 0x000002816B98D820)
0x00007FF71A0DFC6D (0x0000000000034AC0 0x0000000000034AC0 0x0000000000034AC0 0x000002816B98D730)
0x00007FF71A0C7FAE (0x000000828C1FF4B0 0x0000000000000057 0x0000000000000057 0x000000828C1FF880)
0x00007FF71A0C0D00 (0x000000828C1FF840 0x000000828C1FF840 0x0000000000000057 0x000000828C1FF868)
0x00007FF71A0BFC97 (0x000002816DD80DA0 0x0000000000000074 0x000002816D49EE50 0x000002816D49EE50)
0x00007FF71A0B75E3 (0x0000000000000074 0x000000828C1FF8C0 0x000000828C1FFB40 0x000000828C1FF810)
0x00007FF71A0C4913 (0x000002816D49EE50 0x0000000000000000 0x000002816DD80A40 0x0000000000000001)
0x00007FF71A0A43F5 (0x0000000000000000 0x0000000000000074 0x000000828C1FFA80 0x000002816DD80A40)
0x00007FF71A0C3522 (0x0000000400000004 0x000000828AFCDF88 0x0000000000000000 0x000000828C1FFD18)
0x00007FF71A0C205C (0x0000028178D8B990 0x0000000000000000 0x0000000000000005 0x0000000000000005)
0x00007FF71A02DD69 (0x0000028178D8B990 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF71A29F894 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFE1F757034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFE210DD241 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
Press any key to continue . . .

**Comment by jgonzis** [comment]
> Whenever I turn on the lolminer, it will mine anywhere between 2 to 45 minutes before prompting to press any key to continue. This has been going on for about 3 days now and I have not changed anything on my computer in the last week. I have an Asus Tuf 3060ti and using the us1.ethermine.org. Any help will be greatly appreciated since micromanaging this is killing my rates.
> 
> If any more info needed I will supply :D
> 
> Best,
> SynErgi

Try to decrease the memory or push a little bit the Power Limit, to see if the new DAG has made that you need some extra push or that your memory is too high

**Comment by jgonzis** [comment]
> I have been getting the same error when mining Beam on my RX 5600 XT. It seems random to me too since temperatures look like they are within good ranges (all under 90 degrees easily).
> 
> Here is the dump when prompted to "Press any key to continue"
> 
> New job received: 2185029 Difficulty: 512
> 0x00007FF71A0DE51C (0x0000030D92F88D57 0x0000343437353132 0x0000343437353132 0x000002816B98D820)
> 0x00007FF71A0DFC6D (0x0000000000034AC0 0x0000000000034AC0 0x0000000000034AC0 0x000002816B98D730)
> 0x00007FF71A0C7FAE (0x000000828C1FF4B0 0x0000000000000057 0x0000000000000057 0x000000828C1FF880)
> 0x00007FF71A0C0D00 (0x000000828C1FF840 0x000000828C1FF840 0x0000000000000057 0x000000828C1FF868)
> 0x00007FF71A0BFC97 (0x000002816DD80DA0 0x0000000000000074 0x000002816D49EE50 0x000002816D49EE50)
> 0x00007FF71A0B75E3 (0x0000000000000074 0x000000828C1FF8C0 0x000000828C1FFB40 0x000000828C1FF810)
> 0x00007FF71A0C4913 (0x000002816D49EE50 0x0000000000000000 0x000002816DD80A40 0x0000000000000001)
> 0x00007FF71A0A43F5 (0x0000000000000000 0x0000000000000074 0x000000828C1FFA80 0x000002816DD80A40)
> 0x00007FF71A0C3522 (0x0000000400000004 0x000000828AFCDF88 0x0000000000000000 0x000000828C1FFD18)
> 0x00007FF71A0C205C (0x0000028178D8B990 0x0000000000000000 0x0000000000000005 0x0000000000000005)
> 0x00007FF71A02DD69 (0x0000028178D8B990 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FF71A29F894 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
> 0x00007FFE1F757034 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
> 0x00007FFE210DD241 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
> Press any key to continue . . .

90C in CORE is high... sometimes is that you need some extra voltage in the core or the excess of memory OC can make it to crash... 

I suppose you are in Windows... so take out the pause and make a loop in the bat file...

:loop
lolminer.exe --algo ETHASH ...
goto loop

(So delete the pause por the goto loop)
