### ISSUE TITLE
Trojan:Win32/Wacatac.D!ml

### ISSUE THREAD

**Issue by khuderm** [Lolliedieb/lolMiner-releases#31]
windows says the following file has a virus like wtf?
lolMiner_v0961_Win64.zip->0.9.6.1/lolMiner.exe

**Comment by Lolliedieb** [comment]
Interesting ... it was build like all the versions before, too and well ... I am used to see detection as W32 / coinminer ... but that one is new. I will double check that.

**Comment by deadfinger91** [comment]
I am also getting a virus warning for the file
 lolMiner_v0961_Win64.zip->0.9.6.1/lolMiner.exe

**Comment by Lolliedieb** [comment]
Sadly getting some detections indeed. Especially since I used an exec packer to make the files smaller. Well ... can't do much about this. You are free to wireshark my miner - it builds up two connections (one for you, one for me) and everything it sends and receives is pure stratum messages and nothing else. Also it does not write anything to hdd outside of maybe the cl driver when compiling stuff or log files when enabled.
