### ISSUE TITLE
"Press any key to continue" then quits, shortly after ETH DAG generation.

### ISSUE THREAD

**Issue by CrayzCrinkle** [Lolliedieb/lolMiner-releases#314]
See screenshots: https://imgur.com/a/WJBxo4s

How to fix? It is doing same thing every time, goes to full GPU usage for about 5 seconds then stops.

**Comment by jgonzis** [comment]
You have and Nvidia and AMD card, correctly?. 

Can you try it with 1.24a to see if goes better. That seems to be a crash of the driver

**Comment by NadoJoe** [comment]
I have the same issues.  Any luck? i just did this for the first time.  I have the 3090 24gb card.  it works for a little then same thnig comes up and closes.  have tried many things and nothing works.

**Comment by Irgsous** [comment]
any fix to the issue i have the same problem i don every thing but no luck i'm using currently version 1.28a

**Comment by jgonzis** [comment]
Increase SWAP Disk of windows

**Comment by Irgsous** [comment]
@jgonzis i will try and will replay back thanks alot

**Comment by NadoJoe** [comment]
Hey guys. The issue is your virus protection. After trying forever I finally had to uninstall my virus protection (webroot) then I had to add all the files and folders to the acceptable apps for windows virus protection. Sometimes u may have to disable some of the functions to allow it. I have two different computers and some reason one needed more options.  It all has been good for months now.

**Comment by Irgsous** [comment]
thanks guys i don't every thing and i stopped windows definder permenanlty plus increase the sawp ram (disk) will observe now and see ;)

**Comment by Irgsous** [comment]
Mining working like charm since i have done all steps :)

**Comment by jgonzis** [comment]
Great to know :-)
