### ISSUE TITLE
lolminer 1.26 v Windows Defender

### ISSUE THREAD

**Issue by BlindMan64** [Lolliedieb/lolMiner-releases#441]
Windows Defender removed lolminer.exe
Trojan:Win32/Sehyioa.A!cl detected
Screenshot attached
![loldef](https://user-images.githubusercontent.com/62650433/114853395-a5cce780-9ddb-11eb-99dd-7958470a9a05.jpg)

**Comment by Lolliedieb** [comment]
Not sure what this Sehyioa is, but well ... I did sign the .exe in Windows to proof its unmodified since it left my computer. Its signed with my real name and my real address.... Sry, can't say why anti virus detects this, but many engines do not like the fact that it is a packed executable and also contains GPU code. 
Some engines even flag it as coinminer ... well ... thats what its supposed to be

Here is current virustotal report for all engines
https://www.virustotal.com/gui/file/794b37d03568cedd4452a3fba8a5be05f30196a1f17cd03b2981ba66318ac9a6/detection
