### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by sherlock36** [Lolliedieb/lolMiner-releases#444]
('lolMiner.exe' is not an internal or external command, nor is it an executable program
Or batch file.)
This shows on the cmd when I open the "mine_eth_4G.bat"

**Comment by jgonzis** [comment]
> ('lolMiner.exe' is not an internal or external command, nor is it an executable program
> Or batch file.)
> This shows on the cmd when I open the "mine_eth_4G.bat"

That normally happen because the Windows Defender has blocked the file... Try to let the folder as an Exception for the windows Defender.
Other problem is that you try to run it as Administrator, so when you run as Administrator is goes to the folder C:\Windows\System32 to look for lolminer.exe. So it is recommended that you modify the bat file and add before the line: lolminer.exe --algo ...
C:\folder_of_lol_miner\lolminer.exe --algo ...

That will make to search directly on the lolMiner folder.

#452
