### ISSUE TITLE
All devices deselected or failed compatiblity check.

### ISSUE THREAD

**Issue by newtwothis** [Lolliedieb/lolMiner-releases#453]
here are my details. any help would be appreciated.

Setup Miner...
OpenCL driver detected.
Number of OpenCL supported GPUs: 2
No Cuda driver or GPUs detected.
Device 0:
    Name:    AMD Radeon R9 M275X
    Address: 5:0
    Vendor:  Advanced Micro Devices (AMD)
    Drivers: OpenCL
    Memory:  4096 MByte (4046 MByte free)
    Active:  false (Unsupported device or driver version.)
Device 1:
    Name:    Intel(R) HD Graphics 5500
    Address: 4294967295:4294967295
    Vendor:  Intel(R) Corporation
    Drivers: OpenCL
    Memory:  1513 MByte
    Active:  false (not selected)

Connecting to pool...
Connected to us1.ethermine.org:4444  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: 0x6B9aA99F90fA0EF256EB82c8559a810C2d84B4E.lolMinerWorker
New job received: 0xb0cf05 Epoch: 408 Target: 0000000112e0be82
New job received: 0xb0cf05 Epoch: 408 Target: 0000000112e0be82
Start Mining...
All devices deselected or failed compatiblity check. Closing lolMinerPress any key to continue . . .

**Comment by hajoschepel04** [comment]
I have this problem to i tried several coins but it is this same last line all the time

**Comment by pdieppa** [comment]
I thought that card only came with 2gb of VRAM! Interesting

**Comment by Lolliedieb** [comment]
Well I need to admit: I do not have a kernel for mobile GPUs at the moment, because mining with them is often a quite bad idea. 
With this 4G variant one actually could mine something like Beam, but surely not Eth - that DAG will not fit the memory. At the moment no plans to add mobile GPUs though, because the architecture is very old (2014!) and you can't expect any profit from them.
