### ISSUE TITLE
lolminer.exe deleted

### ISSUE THREAD

**Issue by viktor1223** [Lolliedieb/lolMiner-releases#459]
![image](https://user-images.githubusercontent.com/26153327/115479137-c5b63e00-a215-11eb-8a46-6ba013228435.png)

the lolmine.exer is continuously getting deleted from my folder in the middle of mining after about 5 days.  I've tried multiple different versions (1.17, 1.19 1.21 and 1.26) each one has the same problem. 

I know this isn't much information I'm new to debugging this kind of problem. Please let me know if I can provide any additional information or screenshots.

**Comment by cryp-tog** [comment]
It's Windows.  Add an exception in Windows Defender for the whole folder and it will stop happening.

HODL!!!

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/26153327/115479137-c5b63e00-a215-11eb-8a46-6ba013228435.png)
> 
> the lolmine.exer is continuously getting deleted from my folder in the middle of mining after about 5 days. I've tried multiple different versions (1.17, 1.19 1.21 and 1.26) each one has the same problem.
> 
> I know this isn't much information I'm new to debugging this kind of problem. Please let me know if I can provide any additional information or screenshots.

Correctly that's the antivirus and the Windows Defender that is deleting it

**Comment by MasterFuba** [comment]
Hi, I have the same issue and runing F-Secure. This is where i have added the folder and the lolminer.exe as exception.
Without this exclusion the exe is getting removed directly. Now its mining....
BUT after 24h hours the file will be deleted again - same as viktor wrote.
Antivirus does not show up any actions or blocked/removed files. So my guess is that it must be MS Defender as bad guy acting. But I thought that MS Defender is inactive if you have a 3rd party Antivirus installed.
Can it be that MS defender is only partial inactive and also removing suspicious files as kind of backupg antivirus?
Because MS Defender is not active i neither can exclude anything there. All the settings are removed and Win11 direct points to F-Secure and there is everything defined as needed.

Very wired that you cannot define any exclusion in MS defender even if it seems to be active partially. 
I have tried to reactivate MS Defender now, for beeing able to define exclusen. After that i have deactivated defender and reactivated F-Secure again. I hope now MS defender stays calm - lets see what happens next day. 

I don't like how these security apps from MS work. They remove things but don't log it and hide the removal from user.

**Comment by jgonzis** [comment]
That is completely normal in the miners in Windows... you should need to put exception or run in Linux
