### ISSUE TITLE
Segm fault 1.01

### ISSUE THREAD

**Issue by Weaksfx** [Lolliedieb/lolMiner-releases#48]
There is a problem in 1.01
![image](https://user-images.githubusercontent.com/43636645/86116700-8a0b8580-bad6-11ea-90c2-0180404765f5.png)

![image](https://user-images.githubusercontent.com/43636645/86117144-3188b800-bad7-11ea-9acc-d039fd38e970.png)

For ex, in 1.0 there is no such thing. 

Differences in cmd line. 
For 1.0 I use:
/lolMiner -a BEAM-I  --pers GrimmPOW --apiport 5501 --devices ALL --log=on --logfile /var/log/app/miners/lolminer-1.01/2
0200630103158.log --timeprint=on --pool defis.sunpool.top:3333 --user d1d41cea2c7bb57ed9b0471ad47196331b2ae24fa97f12686d8e5f2c74d12bcb.1 --pass x --tls=off 
For 1.01:
/lolMiner -a BEAM-I  --pers GrimmPOW --apiport 5501 --devices ALL --log=on --logfile /var/log/app/miners/lolminer-1.01/2
0200630103158.log --timeprint=on --pool defis.sunpool.top:3333 --user d1d41cea2c7bb57ed9b0471ad47196331b2ae24fa97f12686d8e5f2c74d12bcb.1 --pass x 

without --tls works just fine :(

**Comment by Lolliedieb** [comment]
But why do you try to turn of tls?
The Beam stratum (and so for the forks, Grimm, Defis and Atomi) the default is tls on, because (except for Nicehash) all pools have tls enabled. Since the pool expects an encrypted connection turning tls off can not work with the pools ... 

By the way there are some parameters in your line you do not need. Shortest equivalent for what you run is:

/lolMiner -a BEAM-I --pers GrimmPOW --apiport 5501 --log on --logfile /var/log/app/miners/lolminer-1.01/2
0200630103158.log --timeprint on --pool defis.sunpool.top:3333 --user d1d41cea2c7bb57ed9b0471ad47196331b2ae24fa97f12686d8e5f2c74d12bcb.1 

(note: log file writing was broken in 1.0 and 1.01 ... 1.02 with a fix will come soon)
