### ISSUE TITLE
Unsupported old drivers

### ISSUE THREAD

**Issue by Stargazer77** [Lolliedieb/lolMiner-releases#52]
Hi! Why did you stop supporting old drivers (for Beam, Grin and Cortex)? We have several hundred GPUs(Fiji) on blockchain drivers (windows) and all miners (including yours until recently) perfectly support these drivers, moreover, on some algorithms such as hashimoto and some Cryptonight, they show better results than the latest drivers. And in this situation we need only reinstall the drivers on all machines only for working with BEAM (most likely temporarily). Can you bring back support for old drivers?

**Comment by Lolliedieb** [comment]
I can try to build Beam for Polaris and Blockchain drivers... will test in next version.

(You can help: what is the clversion string of them in Windows? Look in clinfo quite at the top)

**Comment by SomethingGettingWrong** [comment]
@Stargazer77  yeah i definitely understand where your coming from'but, Have you tried the latest 20.7.x drivers? They mine Eth and Beam as good are as the block chain for me. I get 31 mega hash on an old rx480 4gig on phenix-miner as of 7/28/2020 as he did something with the dag.. but on 18.x and 19.x it doesnt work. Phenix worked on blockchain but mining on 4gig doesnt work on it.   I too preferred blockchain as they ran cooler but the last few drivers have been top notched and fixed all the issues of 18.x and 19.x  You should really take the time to look into 20.7.1 because at teh end of the day its only gonna get more unsupported. teamredminer,phoenixminer, are going away from it as well.

**Comment by Stargazer77** [comment]
@Lolliedieb  at top in clinfo i see only this:
"Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (2442.12)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices"

**Comment by Stargazer77** [comment]
@SomethingGettingWrong   rx480 and Fiji  its a different GPUs and they behave completely differently on different drivers and on different algorithms. Here we are talking exclusively about Fury (Fiji) on HBM memory. And all miners on all algorithms work VERY fine with blockchain drivers, at least for today.

**Comment by Stargazer77** [comment]
@Lolliedieb  by the way, 20sol  on BEAM with your 1.0.4 version(tests on separate system with one of last driver, win7). Fiji were monsters then and still are stay them today. Wait for blockchain driver support from you in next version.

**Comment by Lolliedieb** [comment]
@Stargazer77 : tanks for the top of clinfo, that I needed.

But need to correct you: 480 and Fiji are even binary kernel compatible and so much more similar then you might think. Ofc hardware, especially mem size, timings and do on differs a lot.

**Comment by Stargazer77** [comment]
@Lolliedieb I meant that on different drivers they behave differently, and what is good for 480 does not mean that it will be good for Fiji, for example, a good 480 result with Hashimoto on the same driver gave worse results on Fiji than on the blockchain driver, there are drivers that show good results with Fiji on individual algorithms but worse for others, and only blockchain drivers showed stability as a result on all algorithms, so I stopped at them and there is no point in coming up with something while it works. Are binary kernels compatible for vega with Fiji(I guess not)?

**Comment by Lolliedieb** [comment]
No, Fiji and Vegas are not binary compatible - there are quite some instructions that Vegas can do that Fiji is lacking.

**Comment by Lolliedieb** [comment]
Can you test new 1.05 release if your cards boot up with the blockchain driver?

**Comment by Stargazer77** [comment]
Sure

**Comment by Stargazer77** [comment]
Very good result! Was tested on 2 systems. With the same oc settings and the same model of GPU on win10 Blockhain driver gives more on about +12-15% hashrate than on Win7 Adrenalin 20.2.2.(with adrenalin the same result as on 1.04). And I think you can give even more, since the consumption is still relatively small, usually this always meant that you can still improve the result. And in general, I think that you need to give more work to these cards, they are very promising for all algorithms at all times. It is a fact. You can always write to me on Bitcointalk for any tests and questions / suggestions. We corresponded sometimes with you there (user: freedom777).

**Comment by Lolliedieb** [comment]
Great to hear the kernels work fine with the blockchain drivers - although it is confusing that on Adrenaline they are slower since the asm of all kernels for all drivers is the same now. Must either be the paging settings of blockchain (thats supposed to be "compute mode" in Adrenaline) or something that has to do with driver scheduling.

Anyways. New release aimed a lot towards reducing compute overhead, so especially the cards that were not able to saturate memory yet (Fiji cards, 5700 and VII) profited most from the new release. It already is mostly hand written assembly, so its getting hard to squeeze out much more. But I will try ofc ;)

Thanks for feedback.
