### ISSUE TITLE
Shares (A/S/Hw) should i be worried with these numbers? 

### ISSUE THREAD

**Issue by jeffpatel71** [Lolliedieb/lolMiner-releases#547]
After 22 hrs and 30 minutes of mining, my shares look like this. I'm wondering if there are too many hardware rejected shares 
1058/3/56
![image](https://user-images.githubusercontent.com/77821959/117927063-41466f00-b32c-11eb-8c2f-3f74e94f7099.png)

**Comment by jgonzis** [comment]
> After 22 hrs and 30 minutes of mining, my shares look like this. I'm wondering if there are too many hardware rejected shares
> 1058/3/56
> ![image](https://user-images.githubusercontent.com/77821959/117927063-41466f00-b32c-11eb-8c2f-3f74e94f7099.png)

Which version are you using?.... the 56 Hardware it could be and excess of Memory OC. Which Config are you using for Memory OC?

**Comment by jeffpatel71** [comment]
Actually, yesterda

**Comment by jgonzis** [comment]
> ![image](https://user-images.githubusercontent.com/77821959/118343514-222e2400-b55c-11eb-98e6-bfa0b1782b22.png)
> On Reddit, this was how to get maximum performance. That's why I am using these settings

If I can recommend you a better OC with less Hardware errors I recommend you to put Memory Clock to 1000, (the hardware errors are because you have it to high, I hope not too many memory degradation there). 

and also please increase the fan speed to minimum 65%. 37 it is to low and that could be a problem... try to keep the GPU less than 58-59C

If you want to have less Watts also leave Power Limit to 100% and add to the mine_eth.bat --cclk 1350 after the --user !WALLET! that will make that the GPU runs at fixed Clock of 1350 it is a recommended clock for the 3060ti. It will automatic be reduced the Watts so you don't need to worry about the Power Limit. If you want you can share you mine_eth.bat before you launch it. 

So 3 points:
--cclck 1350
Memory OC 1000 to avoid hardware errors
Fan Speed higher to less Temp

**Comment by jeffpatel71** [comment]
![image](https://user-images.githubusercontent.com/77821959/118354097-05194580-b59c-11eb-8466-2cf3ff0388fd.png)
Here are my settings... but after launching it gave the unrecognised option error
![image](https://user-images.githubusercontent.com/77821959/118354145-31cd5d00-b59c-11eb-9862-c1c22a944615.png)

**Comment by jgonzis** [comment]
Try 1.28a and with cclk you have put cclck

**Comment by jeffpatel71** [comment]
it runs.. but it says insufficient permissions for this operation

**Comment by jgonzis** [comment]
> it runs.. but it says insufficient permissions for this operation
> ![image](https://user-images.githubusercontent.com/77821959/118360839-83391480-b5bb-11eb-8d47-59c8bc502747.png)
> How do I give it permission?

You have to run it as Administrator

**Comment by jeffpatel71** [comment]
It works. <3

**Comment by jgonzis** [comment]
> It works. <3.. But when I open another app, the core clock remains at 1350. How do I change that...

You can reset profile from MSI Afterburner or restarts Windows always works

**Comment by jgonzis** [comment]
No problem or feedback... close issue
