### ISSUE TITLE
Log does not work

### ISSUE THREAD

**Issue by kr-deps** [Lolliedieb/lolMiner-releases#55]
The miner locks the log file and I cannot open it with notepad while mining (Windows).

Also, `--log` and `--logfile` options are too much. One `--logfile` option is enough (no filename - no log).

**Comment by Lolliedieb** [comment]
Well they both serve a purpose, namely "--log on" will activate writing into a log file in ./logs folder (the folder needs to exist, else no log file is written) with a file name given by startup time. 
So there is a difference between printing logs or not. 
Well on the other hand you are right - when a user uses the logfile option that should trigger --log on automatically. Will be fixed in next version. 

Wrt the read access: good catch. Next version should grant read access for other processes to the log file while the miner is writing to it.

**Comment by kakyke** [comment]
is there a way to possible append previous log to add to end. is it possible to make it so it does not delete the previous log
