### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Darthsnarf** [Lolliedieb/lolMiner-releases#602]
![image](https://user-images.githubusercontent.com/84875234/119722616-23036780-be32-11eb-81f1-0507b2a942ff.png)

No idea what happened.  I used the miner for the last month with no issues and now I get this all of a sudden.

**Comment by pdieppa** [comment]
Most likely your anti-virus picked it up and moved it to quarantine. Make sure you add an exception in your AV setting for the directory where the miner is located.

**Comment by Darthsnarf** [comment]
Tried it and that didn't do it.

**Comment by pdieppa** [comment]
Did you download the program again after adding the exceptions in your AV and Windows Defender?

**Comment by Darthsnarf** [comment]
Just redownloaded and does the same thing.

**Comment by pdieppa** [comment]
The error you are receiving says the file is missing. 
Can you post a copy of the batch file you are using?
Also, can you post a screenshot of your directory where all the lolMiner files reside?

**Comment by Darthsnarf** [comment]
![image](https://user-images.githubusercontent.com/84875234/119932704-f9892f80-bf48-11eb-980b-0a11d00fc4ba.png)

![image](https://user-images.githubusercontent.com/84875234/119933151-250c1a00-bf49-11eb-87d1-83ad419d8873.png)

I took my wallet address out so I feel safer.  Maybe not required but I am very new to all this and wasn't sure.

**Comment by pdieppa** [comment]
If you look at your directory, you will see that the executable lolminer.exe is missing. That is the reason why you are getting that error. I am 99% sure this is happening because your anti-virus is removing the file from the directory and placing it under its quarantine directory.

The reason is that most if not all crypto currency miners are flagged as malware. This is why you must disable your AV before you download and copy the miners to their directories. In your case D:\mining. You must also do the same to Windows Defender

Add an exclusion to Windows Security
If you trust a file, file type, folder, or a process that Windows Security has detected as malicious, you can stop Windows Security from alerting you or blocking the program by adding the file to the exclusions list. 
1
Go to Start Windows logo Start button > Settings Gear-shaped Settings icon > Update & Security Circular arrows Sync icon > Windows Security > Virus & threat protection.
2
Under Virus & threat protection settings, select Manage settings, and then under Exclusions, select Add or remove exclusions.
The Exclusions page of Windows Security Virus & Threat Protection.
3
Select Add an exclusion, and then select from files, folders, file types, or process. A folder exclusion will apply to all subfolders within the folder as well.

**Comment by Darthsnarf** [comment]
It was in my antivirus quarantine section.  Restored it and it tried connecting at least but timed out.  Weird because I didn't change anything and decided to give my computer a break and shut it down for the night.  Next day it blocked it.  Oh well.  Just happy it's working again.  Thank you for your help.  It is highly appreciated.

**Comment by pdieppa** [comment]
Great. Make sure you create the exception for the directory or the same thing could happen next time the av does a scan. Happy mining.
