### ISSUE TITLE
Uneven GPUs Hashrate 

### ISSUE THREAD

**Issue by Niko585** [Lolliedieb/lolMiner-releases#706]
I thought it was over heating so I put them on risers, thought it was a power problem so I got another psu.  For the life of me I can figure out why the GPUs are uneven, with only one at max hashrate. 

System specs:
TB360 BTC D+ MOBO
Intel Celeron G4900 3.10 ghz
8gb RAM
1200w psu bitmain apw++
4x 3080 FE

The cards are framed the same distance apart so, can be overheating if one of the cards still performs at max hashrate?

Page file size is 32gb, same thing at 70gb. 4g encoding, 1 Gen pcie

Power lowers on some cards, some are not even at the vram temp max. Again, I tried with two of the power supplies at the same time, and still no fix.

**Comment by Niko585** [comment]
Forgot to mention I have 4x 3080 FR

**Comment by Niko585** [comment]
Founders edition*

**Comment by Niko585** [comment]
![Uploading 16293227310348806199084183764275.jpg…]()

**Comment by Niko585** [comment]
![Uploading 16293228073835017601737242711718.jpg…]()

**Comment by Niko585** [comment]
![20210818_174150](https://user-images.githubusercontent.com/89165444/129976073-e3be7b39-12d0-4f51-8490-54987c619aee.jpg)

**Comment by jgonzis** [comment]
3080 FE have problems with Memory OC. You are in Windows so you can open GPU-Z and see the memory temp. You will see that your memory is overheating, more than 100C. The GPU automatically autoprotects himself reducing speed. That's why you are not able to achieve the desidered Mhs. You can try to put fresh air, or the normally solution is to open them and put better thermal pads. 12W or 12.8W pads.

**Comment by jgonzis** [comment]
No problem or feedback... close issue
