### ISSUE TITLE
Ergo (Autolykos2) Unstable Hashrate ...

### ISSUE THREAD

**Issue by profanx** [Lolliedieb/lolMiner-releases#707]
Hello 
when i am using Nanominer everything is OK. Hashrate is stable and everytime is 251MH
But when i am using Lolminer the hashrate is not stable, sometimes 251MH, sometimes 178 MH , sometimes 201 MH. Everytime different. WHY?

am i doing something wrong when i am using Lol Miner?
Thanks.

**Comment by jgonzis** [comment]
> Hello
> when i am using Nanominer everything is OK. Hashrate is stable and everytime is 251MH
> But when i am using Lolminer the hashrate is not stable, sometimes 251MH, sometimes 178 MH , sometimes 201 MH. Everytime different. WHY?
> 
> am i doing something wrong when i am using Lol Miner?
> Thanks.

That's completely normal, don't worry. ERGO must do Dataset each several times, sometimes 4 in a minute. During that Dataset is not possible to mine, this is why the hashrate drops, and returns. If you find others miners that don't drop During the Dataset, you should not be confident with that, because during Dataset is impossible to mine. So any hashrate there is not true.

**Comment by i1itione** [comment]
It seems that there is LHR lock when mining ERGO with RTX 3080 Ti which is using higher MEM clock, but it is able to bypass (unlock) in the latest version of nbminer currently. Will lolMiner add this feature? Thanks.

**Comment by jgonzis** [comment]
With new Nvidia Driver all done.
