### ISSUE TITLE
lolMiner trojan files

### ISSUE THREAD

**Issue by peter71363** [Lolliedieb/lolMiner-releases#724]
hello, I downloaded lolMiner 1.31 and these files were found and quarantined by windows defender
Trojan:Script/Wacatac.B!ml
Trojan:Script/Oneeva.A!ml
they were both found in lolMiner_v1.31_Win64\1.31\mine_eth.bat
should I allow them? what should I do?

**Comment by bbwin90** [comment]
yes allow them most mining software is flagged as malicious.

**Comment by vmcriptos** [comment]
Allow them???? Dude, he just found 2 dangerous trojans in the file, like says these pages on Malware Fixes: 
https://malwarefixes.com/threats/how-to-remove-trojanscript-oneeva-aml/
https://malwarefixes.com/threats/trojanscript-wacatac-bml/
If they aren't false positives, this miner can most likely harm our computers or steal our data soon. Hey peter, try to install another antivirus and check the file again. Upload the file on "https://www.virustotal.com/gui/home/upload" too.

**Comment by AP4130** [comment]
Same issue here; I've been using lolMiner since 1.21 without any issues. Had to allow CoinMiner and Pearfoos.A!ml in Windows Defender as low severity threats, but no other issues.

Suddenly this morning, with no user changes to lolMiner 1.31, Windows quarantined mine_eth.bat as a severe threat due to Trojan:Win32/Wacatac.B!ml. I tried redownloading the package to scan a fresh copy, and it quarantined the whole .zip as a severe threat due to Trojan:Win32/Vigorf.A

**Comment by jgonzis** [comment]
Download always from official site github

As the colleague said: "yes allow them most mining software is flagged as malicious."
