### ISSUE TITLE
Add socks5 proxy！

### ISSUE THREAD

**Issue by liukaixin007** [Lolliedieb/lolMiner-releases#876]
Add socks5 proxy，Will be useful to a very large number of people！

**Comment by jgonzis** [comment]
New Realease will come with new implentation to avoid problem with the Firewall it will very soon released

**Comment by jgonzis** [comment]
Could you try new 1.38, to see if that helps you?

**Comment by liukaixin007** [comment]
Can't use --proxy! SOCKS5 is not supported?

**Comment by nathanfleight** [comment]
DNS over HTTPS somewhat helps but not as explicitly specifying your own socks5.

A practical use case would be: create a socks5 tunnel via ssh by executing ssh ubuntu@1.2.3.4 -o StrictHostKeyChecking=no -D 1338 -f -C -q -N -i key.pem -p 443

Then execute:

./lolMiner -a ethash -o stratum+ssl://eth-us-west.flexpool.io:5555 -u 0x..............xxxxxx -p x --worker Test --proxy 127.0.0.1:1338

**Comment by Lbritton702** [comment]
Thank you guys!!!

**Comment by Lbritton702** [comment]
Thank you guys!!!

**Comment by ComputeLabsLTD** [comment]
In my opinion the DNS over HTTPS helps even more, because the default connection with a socks5 server is not encrypted and thus vulnerable to man in the middle attacks - this is something that you do not have when directly connecting to pool with TLS and used DoH before. 

Anyways, if you with socks5 ... that is something we can do for you :)

**Comment by Lolliedieb** [comment]
In my opinion the DNS over HTTPS helps even more, because the default connection with a socks5 server is not encrypted and thus vulnerable to man in the middle attacks - this is something that you do not have when directly connecting to pool with TLS and used DoH before.

Anyways, if you with socks5 ... that is something we can do for you :)
Planning to add it in 1.39 if technically possible :)

**Comment by chraac** [comment]
> In my opinion the DNS over HTTPS helps even more, because the default connection with a socks5 server is not encrypted and thus vulnerable to man in the middle attacks - this is something that you do not have when directly connecting to pool with TLS and used DoH before.
> 
> Anyways, if you with socks5 ... that is something we can do for you :) Planning to add it in 1.39 if technically possible :)

A typical use case of socks5 is by some tunnel software listening at local address and then the application will easy to connnet to it. And often, the tunnel software will have an encrypted outbound connection to remote server. So for this case I think there is no concern about the MITM attack.

**Comment by liukaixin007** [comment]
Support agents are great! It is hoped that the development cost can also use the proxy line

**Comment by jgonzis** [comment]
> Support agents are great! It is hoped that the development cost can also use the proxy line

Socks5 added in 1.39
